# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\BaiduSyncdisk\开发文件\Preboot eXecution Environment\UI\DEPLOY.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DEPLOY(object):
    def setupUi(self, DEPLOY):
        DEPLOY.setObjectName("DEPLOY")
        DEPLOY.resize(800, 700)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DEPLOY.sizePolicy().hasHeightForWidth())
        DEPLOY.setSizePolicy(sizePolicy)
        DEPLOY.setMinimumSize(QtCore.QSize(800, 700))
        DEPLOY.setMaximumSize(QtCore.QSize(800, 700))
        self.verticalLayout = QtWidgets.QVBoxLayout(DEPLOY)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_NetName = QtWidgets.QGroupBox(DEPLOY)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_NetName.sizePolicy().hasHeightForWidth())
        self.groupBox_NetName.setSizePolicy(sizePolicy)
        self.groupBox_NetName.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_NetName.setMaximumSize(QtCore.QSize(9999, 60))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.groupBox_NetName.setFont(font)
        self.groupBox_NetName.setObjectName("groupBox_NetName")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.groupBox_NetName)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.PrimaryToolButton_DHCP = PrimaryToolButton(self.groupBox_NetName)
        self.PrimaryToolButton_DHCP.setMaximumSize(QtCore.QSize(15, 15))
        self.PrimaryToolButton_DHCP.setObjectName("PrimaryToolButton_DHCP")
        self.horizontalLayout_8.addWidget(self.PrimaryToolButton_DHCP)
        self.BodyLabel = BodyLabel(self.groupBox_NetName)
        self.BodyLabel.setObjectName("BodyLabel")
        self.horizontalLayout_8.addWidget(self.BodyLabel)
        self.PrimaryToolButton_TFTP = PrimaryToolButton(self.groupBox_NetName)
        self.PrimaryToolButton_TFTP.setMaximumSize(QtCore.QSize(15, 15))
        self.PrimaryToolButton_TFTP.setObjectName("PrimaryToolButton_TFTP")
        self.horizontalLayout_8.addWidget(self.PrimaryToolButton_TFTP)
        self.BodyLabel_2 = BodyLabel(self.groupBox_NetName)
        self.BodyLabel_2.setObjectName("BodyLabel_2")
        self.horizontalLayout_8.addWidget(self.BodyLabel_2)
        self.PrimaryToolButton_NFS = PrimaryToolButton(self.groupBox_NetName)
        self.PrimaryToolButton_NFS.setMaximumSize(QtCore.QSize(15, 15))
        self.PrimaryToolButton_NFS.setObjectName("PrimaryToolButton_NFS")
        self.horizontalLayout_8.addWidget(self.PrimaryToolButton_NFS)
        self.BodyLabel_3 = BodyLabel(self.groupBox_NetName)
        self.BodyLabel_3.setObjectName("BodyLabel_3")
        self.horizontalLayout_8.addWidget(self.BodyLabel_3)
        self.PrimaryToolButton_HTTPD = PrimaryToolButton(self.groupBox_NetName)
        self.PrimaryToolButton_HTTPD.setMaximumSize(QtCore.QSize(15, 15))
        self.PrimaryToolButton_HTTPD.setObjectName("PrimaryToolButton_HTTPD")
        self.horizontalLayout_8.addWidget(self.PrimaryToolButton_HTTPD)
        self.BodyLabel_4 = BodyLabel(self.groupBox_NetName)
        self.BodyLabel_4.setObjectName("BodyLabel_4")
        self.horizontalLayout_8.addWidget(self.BodyLabel_4)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem)
        self.verticalLayout.addWidget(self.groupBox_NetName)
        self.PlainTextEdit = QtWidgets.QPlainTextEdit(DEPLOY)
        self.PlainTextEdit.setObjectName("PlainTextEdit")
        self.verticalLayout.addWidget(self.PlainTextEdit)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.PrimaryPushButton = PrimaryPushButton(DEPLOY)
        self.PrimaryPushButton.setObjectName("PrimaryPushButton")
        self.horizontalLayout.addWidget(self.PrimaryPushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(DEPLOY)
        QtCore.QMetaObject.connectSlotsByName(DEPLOY)

    def retranslateUi(self, DEPLOY):
        _translate = QtCore.QCoreApplication.translate
        DEPLOY.setWindowTitle(_translate("DEPLOY", "Form"))
        self.groupBox_NetName.setTitle(_translate("DEPLOY", "组件状态"))
        self.BodyLabel.setText(_translate("DEPLOY", "DHCP"))
        self.BodyLabel_2.setText(_translate("DEPLOY", "TFTP"))
        self.BodyLabel_3.setText(_translate("DEPLOY", "NFS"))
        self.BodyLabel_4.setText(_translate("DEPLOY", "HTTPD"))
        self.PrimaryPushButton.setText(_translate("DEPLOY", "开始部署"))
from qfluentwidgets import BodyLabel, PrimaryPushButton, PrimaryToolButton
